# -*- coding: utf-8 -*-

""" EBarimt Constants """

DEFAULT_AIMAG_CITY_CODE = '23'
TAX_TYPE_VAT = 'TAX_TYPE_VAT'
TAX_TYPE_CITY = 'TAX_TYPE_CITY'
TAX_TYPE_VAT_FREE = 'TAX_TYPE_VAT_FREE'
TAX_TYPE_VAT_ZERO = 'TAX_TYPE_VAT_ZERO'

BILL_TYPE_NOTAX = '0'
BILL_TYPE_INDIVIDUAL = 'B2C_RECEIPT'
BILL_TYPE_COMPANY = 'B2B_RECEIPT'
BILL_TYPE_INVOICE = 'B2C_INVOICE'
BILL_TYPE_B2B_INVOICE = 'B2B_INVOICE'
