
{
    'name' : 'MW HSE',
    'version' : '0.1',
    'license': 'LGPL-3',
    'author' : 'Managewall LLC by Odka',
    'website' : 'http://www.managewall.mn/',
    'category' : 'ХАБ Модуль',
    'description': 'Mongolian mining operator company',
    'depends' : ['base','mw_hr','mw_hr_additional','mw_stock','branch','mw_dynamic_flow','populating_ms_word_template'],
    'data' : [
            'security/hse_security.xml',
            'security/ir.model.access.csv',
            'views/hse_config_view.xml',
            'views/hse_daily_report_view.xml',
            'views/hse_injury_entry_view.xml',
            'views/hse_hazard_report_view.xml',
            'views/hse_workplace_inspection_view.xml',
            'views/hse_discipline_action_view.xml',
            'views/hse_risk_assessment_view.xml',
            'views/hse_risk_assessment_workplace_view.xml',
            'views/hse_preliminary_notice_view.xml',
            'views/hse_warning_page_view.xml',
            'views/hse_salary_kpi.xml',
            'views/hse_accident_research_act_view.xml',
            'views/hse_document_view.xml',
            'views/hse_mission_view.xml',
            'report/workplace_inspection_report.xml',
            'report/wizard_hse_daily_report.xml',
            'report/hse_water_registration_report.xml',
            'report/hse_danger_registration_report.xml',
            'views/menu_view.xml',
    ],
    'icon': '/mw_hse/static/img/hse_icon.png',
    'init_xml' : [],
    'demo_xml' : [],
    'update_xml' : [],
    'installable': True,
    'application': False,
    'auto_install': False,
}