# -*- coding: utf-8 -*-
{
    'name' : 'MW HSE Health',
    'version' : '0.1',
    'license': 'LGPL-3', 
    'author' : 'Managewall LLC by Odka',
    'website' : 'http://www.managewall.mn/',
    'category' : 'MW Hse',
    'description': 'ХАБ Эрүүл мэнд',
    'depends' : ['base','mw_hr','mw_hse'],
    'data'   :  [
        'security/hse_health_security.xml',
        'security/ir.model.access.csv',
        'views/hse_health_view.xml',
        'views/hse_health_reference_view.xml',
        'views/drug_revenue_view.xml',
        'views/hse_ambulance_view.xml',
        'views/hse_health_analysis_view.xml',
        'views/health_treatment_view.xml',
        'views/menu_view.xml',
    ],
    'init_xml' : [ ],
    'demo_xml' : [ ],
    'update_xml' : [],
    'installable': True,
    'application': True,
    'auto_install': False,
}