# -*- coding: utf-8 -*-
{
    "name": "MW Environment",
    "version": "0.1",
    'license': 'LGPL-3',
    "author": "Managewall LLC",
    'website' : 'http://www.managewall.mn/',
    "category": "MW HSE",
    "description": """Байгаль Орчны модуль""",
    "website": True,
    "depends": ['web','base','account_asset','mw_asset','mw_base','web_map','hr','mw_hr','mw_dynamic_flow','web_view_google_map','mw_technic_equipment'],
    "init": [],
    "data": [
        'security/security.xml',
        'security/ir.model.access.csv',
        # 'views/env_gmaps_assets.xml',
        'views/env_training.xml',
        'views/env_accident.xml',
        'views/env_inspection_view.xml',
        'views/env_water_view.xml',
        'views/env_waste_view.xml',
        'views/env_rehab.xml',
        'views/env_animal.xml',
        'views/env_expense.xml',
        'views/env_garden.xml',
        'views/env_tree.xml',
        'views/env_monitor_air.xml',
        'views/env_monitor_animal.xml',
        'views/env_monitor_plant.xml',
        'views/env_monitor_soil.xml',
        'views/env_monitor_water.xml',
        'views/env_monitor_noise.xml',
        'views/env_mining.xml',
        'views/env_parameter.xml',
        'views/env_standard.xml',
        'views/env_monitoring_items.xml',
        'views/env_approved_view.xml',
        'views/greenhouse_gas_view.xml',
        'views/env_gas_approved_view.xml',
        'reports/env_paper_format.xml',
        'reports/env_report_template.xml',
        'reports/env_monitor_report_template.xml',
        'reports/env_tree_report_template.xml',
        'reports/env_monthly_report.xml',
        'reports/env_seasonal_report.xml',
        'reports/env_monitor_report.xml',
        'reports/env_tree_report.xml',
        'reports/consolidated_report.xml',
        'reports/consolidated_gas_report_view.xml',
        'views/menu_view.xml',
    ],
    "demo_xml": [],
    'icon': '/mw_environment/static/src/img/environment_logo.png',
    "installable": True,
    'application': False,
    'auto_install': False,
    'assets' : {
		'web.assets_frontend': [
				'/mining16/mw_environment/static/js/map_views.js'
				],
        # 'web.assets_common': [
        #     '/mining16/mw_environment/static/src/css/map_view.css'
        # ],
        # 'web.assets_qweb': [
        #     'mw_timetable/static/src/xml/map_view.xml',
        # ],
    }
}
