
from odoo import fields, models
from datetime import datetime, timedelta
from io import BytesIO
import xlsxwriter
from odoo.exceptions import UserError
import base64

class SalePlan(models.Model):
	_name='sale.plan'
	_description = 'Sale Plan'
	_inherit = ['mail.thread']

	name = fields.Char('Нэр', required=True)
	line_ids = fields.One2many('sale.plan.line', 'parent_id', 'Мөр',required=True)
	line_ids2 = fields.One2many('sale.plan.line.second', 'parent_id', 'Мөр',required=True)
	line_ids3 = fields.One2many('sale.plan.line.third', 'parent_id', 'Мөр',required=True)
	year = fields.Selection(selection='years_selection', string="Жил",required=True)
	season = fields.Selection([('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], 'Улирал')

	def years_selection(self):
		year_list = []
		for y in range(datetime.now().year, datetime.now().year+1):
			year_list.append((str(y), str(y)))
		return year_list

	def download_report(self):
		if len(self.line_ids.mapped('type'))!=2:
			raise UserError("Эхний төлөвлөгөө зөв оруулна уу!")
		if len(self.line_ids2.mapped('type'))!=2:
			raise UserError("Хүлээгдэж буй бодит зөв оруулна уу!")
		if not self.line_ids3:
			raise UserError("Мөнгөн урсгал, хүлээгдэж буй бодит оруулаагүй байна!")
		if self.season == '1':
			s = 1
			col = 0
		elif self.season == '2':
			s = 2
			col = 3
		elif self.season == '3':
			s = 3
			col = 6
		elif self.season == '4':
			s = 4
			col = 9
		else:
			raise UserError(u'Тайлан татах улирал сонгоно уу.')

		output = BytesIO()
		workbook = xlsxwriter.Workbook(output)
		file_name = 'БОРЛУУЛАЛТЫН ДҮНГИЙН ГҮЙЦЭТГЭЛИЙН ТАЙЛАН.xlsx'

		h1 = workbook.add_format({})
		h1.set_font_size(12)
		h1.set_align('center')
		h1.set_align('vcenter')

		contest_center = workbook.add_format({'num_format': '###,###,###.##'})
		contest_center.set_text_wrap()
		contest_center.set_font_size(9)
		contest_center.set_font('Times new roman')
		contest_center.set_align('center')
		contest_center.set_align('vcenter')
		contest_center.set_border(style=1)

		sheet = workbook.add_worksheet(u'ТАЙЛАН')
		if self.line_ids:
			sheet.set_column(0,0,5)
			sheet.set_column(1,1,20)
			sheet.set_column(2,2,5)
			sheet.set_column(3,3,20)
			sheet.set_column(4,4,20)
			sheet.set_column(5,5,20)
			sheet.set_column(6,6,20)
			sheet.set_column(7,7,20)
			sheet.set_column(8,8,20)
			sheet.set_column(9,9,20)
			sheet.set_column(10,10,20)
			sheet.set_column(11,11,20)
			sheet.set_column(12,12,20)
			sheet.set_column(13,13,20)
			sheet.set_column(14,14,20)
			sheet.set_column(15,15,20)
			sheet.set_column(16,16,20)
			sheet.set_column(17,17,20)
			sale_order = self.env['sale.order']
			sale_order_line = self.env['sale.order.line']
			sheet.merge_range(0, 0, 0, 17, u'БОРЛУУЛАЛТЫН ДҮНГИЙН ГҮЙЦЭТГЭЛИЙН ТАЙЛАН', h1)
			sheet.write(1, 1, u'Борлуулалтын тайлан, нэгтгэл', contest_center)
			sheet.merge_range(2, 0, 3, 0, u'№', contest_center)
			sheet.merge_range(2, 1, 3, 1, u'Нэр', contest_center)
			sheet.merge_range(2, 2, 3, 2, u'Нэгж', contest_center)
			sheet.merge_range(2, 3, 2, 7, str(s)+u'-р улирал', contest_center)
			sheet.write(3, 3, u'Эхний төлөвлөгөө', contest_center)
			sheet.write(3, 4, u'Тооцсон /хүлээгдэж буй/', contest_center)
			sheet.write(3, 5, u'Бодит гүйцэтгэл', contest_center)
			sheet.write(3, 6, u'Бодит гүйцэтгэл / Эхний, %', contest_center)
			sheet.write(3, 7, u'Бодит гүйцэтгэл / Тооцсон, %', contest_center)
			sheet.merge_range(2, 8, 2, 12, u'Өссөн дүнгээр, YTM (year to month)', contest_center)
			sheet.write(3, 8, u'Эхний төлөвлөгөө', contest_center)
			sheet.write(3, 9, u'Тооцсон /хүлээгдэж буй/', contest_center)
			sheet.write(3, 10, u'Бодит гүйцэтгэл', contest_center)
			sheet.write(3, 11, u'Бодит гүйцэтгэл / Эхний, %', contest_center)
			sheet.write(3, 12, u'Бодит гүйцэтгэл / Тооцсон, %', contest_center)
			sheet.merge_range(2, 13, 2, 17, u'Жил', contest_center)
			sheet.write(3, 13, u'Эхний төлөвлөгөө', contest_center)
			sheet.write(3, 14, u'Тооцсон /хүлээгдэж буй/', contest_center)
			sheet.write(3, 15, u'Бодит гүйцэтгэл', contest_center)
			sheet.write(3, 16, u'Бодит гүйцэтгэл / Эхний, %', contest_center)
			sheet.write(3, 17, u'Бодит гүйцэтгэл / Тооцсон, %', contest_center)
			sheet.write(4, 0, u'1', contest_center)
			sheet.write(4, 1, u'Борлуулалт', contest_center)
			sheet.write(4, 2, u'₮', contest_center)
			sheet.write(5, 0, u'2', contest_center)
			sheet.write(5, 1, u'Борлуулалтын өртөг', contest_center)
			sheet.write(5, 2, u'₮', contest_center)
			sheet.write(6, 0, u'3', contest_center)
			sheet.write(6, 1, u'Борлуулалтын (бохир) ашиг', contest_center)
			sheet.write(6, 2, u'₮', contest_center)
			sheet.write(7, 0, u'4', contest_center)
			sheet.write(7, 1, u'Борлуулалтанд эзлэх өртгийн %', contest_center)
			sheet.write(7, 2, u'%', contest_center)
			sheet.write(8, 0, u'5', contest_center)
			sheet.write(8, 1, u'Борлуулалтанд эзлэх ашгийн %', contest_center)
			sheet.write(8, 2, u'%', contest_center)

			sheet.write(1+9, 1, u'Борлуулалтын тайлан, /ханган нийлүүлэлт/', contest_center)
			sheet.merge_range(2+9, 0, 3+9, 0, u'№', contest_center)
			sheet.merge_range(2+9, 1, 3+9, 1, u'Нэр', contest_center)
			sheet.merge_range(2+9, 2, 3+9, 2, u'Нэгж', contest_center)
			sheet.merge_range(2+9, 3, 2+9, 7, str(s)+u'-р улирал', contest_center)
			sheet.write(3+9, 3, u'Эхний төлөвлөгөө', contest_center)
			sheet.write(3+9, 4, u'Тооцсон /хүлээгдэж буй/', contest_center)
			sheet.write(3+9, 5, u'Бодит гүйцэтгэл', contest_center)
			sheet.write(3+9, 6, u'Бодит гүйцэтгэл / Эхний, %', contest_center)
			sheet.write(3+9, 7, u'Бодит гүйцэтгэл / Тооцсон, %', contest_center)
			sheet.write(4+9, 0, u'1', contest_center)
			sheet.write(4+9, 1, u'Борлуулалт', contest_center)
			sheet.write(4+9, 2, u'₮', contest_center)
			sheet.write(5+9, 0, u'2', contest_center)
			sheet.write(5+9, 1, u'Борлуулалтын өртөг', contest_center)
			sheet.write(5+9, 2, u'₮', contest_center)
			sheet.write(6+9, 0, u'3', contest_center)
			sheet.write(6+9, 1, u'Борлуулалтын (бохир) ашиг', contest_center)
			sheet.write(6+9, 2, u'₮', contest_center)
			sheet.write(7+9, 0, u'4', contest_center)
			sheet.write(7+9, 1, u'Борлуулалтанд эзлэх өртгийн %', contest_center)
			sheet.write(7+9, 2, u'%', contest_center)
			sheet.write(8+9, 0, u'5', contest_center)
			sheet.write(8+9, 1, u'Борлуулалтанд эзлэх ашгийн %', contest_center)
			sheet.write(8+9, 2, u'%', contest_center)

			sheet.write(1+18, 1, u'Борлуулалтын тайлан, /ашиглалт, угсралт/', contest_center)
			sheet.merge_range(2+18, 0, 3+18, 0, u'№', contest_center)
			sheet.merge_range(2+18, 1, 3+18, 1, u'Нэр', contest_center)
			sheet.merge_range(2+18, 2, 3+18, 2, u'Нэгж', contest_center)
			sheet.merge_range(2+18, 3, 2+18, 7, str(s)+u'-р улирал', contest_center)
			sheet.write(3+18, 3, u'Эхний төлөвлөгөө', contest_center)
			sheet.write(3+18, 4, u'Тооцсон /хүлээгдэж буй/', contest_center)
			sheet.write(3+18, 5, u'Бодит гүйцэтгэл', contest_center)
			sheet.write(3+18, 6, u'Бодит гүйцэтгэл / Эхний, %', contest_center)
			sheet.write(3+18, 7, u'Бодит гүйцэтгэл / Тооцсон, %', contest_center)
			sheet.write(4+18, 0, u'1', contest_center)
			sheet.write(4+18, 1, u'Борлуулалт', contest_center)
			sheet.write(4+18, 2, u'₮', contest_center)
			sheet.write(5+18, 0, u'2', contest_center)
			sheet.write(5+18, 1, u'Борлуулалтын өртөг', contest_center)
			sheet.write(5+18, 2, u'₮', contest_center)
			sheet.write(6+18, 0, u'3', contest_center)
			sheet.write(6+18, 1, u'Борлуулалтын (бохир) ашиг', contest_center)
			sheet.write(6+18, 2, u'₮', contest_center)
			sheet.write(7+18, 0, u'4', contest_center)
			sheet.write(7+18, 1, u'Борлуулалтанд эзлэх өртгийн %', contest_center)
			sheet.write(7+18, 2, u'%', contest_center)
			sheet.write(8+18, 0, u'5', contest_center)
			sheet.write(8+18, 1, u'Борлуулалтанд эзлэх ашгийн %', contest_center)
			sheet.write(8+18, 2, u'%', contest_center)

			sheet.write(1+27, 1, u'Борлуулалтын тайлан /Ханган нийлүүлэлт/', contest_center)
			sheet.merge_range(2+27, 0, 3+27, 0, u'№', contest_center)
			sheet.merge_range(2+27, 1, 3+27, 1, u'Нэр', contest_center)
			sheet.merge_range(2+27, 2, 3+27, 2, u'Нэгж', contest_center)
			sheet.merge_range(2+27, 3, 3+27, 3, u'Нийт', contest_center)
			sheet.merge_range(2+27, 4, 2+27, 15, self.year, contest_center)
			sheet.write(3+27, 4, u'1', contest_center)
			sheet.write(3+27, 5, u'2', contest_center)
			sheet.write(3+27, 6, u'3', contest_center)
			sheet.write(3+27, 7, u'4', contest_center)
			sheet.write(3+27, 8, u'5', contest_center)
			sheet.write(3+27, 9, u'6', contest_center)
			sheet.write(3+27, 10, u'7', contest_center)
			sheet.write(3+27, 11, u'8', contest_center)
			sheet.write(3+27, 12, u'9', contest_center)
			sheet.write(3+27, 13, u'10', contest_center)
			sheet.write(3+27, 14, u'11', contest_center)
			sheet.write(3+27, 15, u'12', contest_center)
			sheet.write(4+27, 0, u'1', contest_center)
			sheet.write(4+27, 1, u'Борлуулалт, Эхний төлөвлөгөө', contest_center)
			sheet.write(4+27, 2, u'₮', contest_center)
			sheet.write(5+27, 0, u'2', contest_center)
			sheet.write(5+27, 1, u'Борлуулалт, Хүлээгдэж буй бодит', contest_center)
			sheet.write(5+27, 2, u'₮', contest_center)
			sheet.write(6+27, 0, u'2', contest_center)
			sheet.write(6+27, 1, u'Хүлээгдэж буй / Эхний төлөвлөгөө, харьцаа', contest_center)
			sheet.write(6+27, 2, u'%', contest_center)
			sheet.write(7+27, 0, u'3', contest_center)
			sheet.write(7+27, 1, u'Борлуулалт, Гүйцэтгэсэн бодит', contest_center)
			sheet.write(7+27, 2, u'₮', contest_center)
			sheet.write(8+27, 0, u'3', contest_center)
			sheet.write(8+27, 1, u'Гүйцэтгэсэн / Эхний төлөвлөгөө, харьцаа', contest_center)
			sheet.write(8+27, 2, u'%', contest_center)
			sheet.write(9+27, 0, u'3', contest_center)
			sheet.write(9+27, 1, u'Гүйцэтгэсэн / Хүлээгдэж буй бодит, харьцаа', contest_center)
			sheet.write(9+27, 2, u'%', contest_center)

			sheet.write(1+37, 1, u'Борлуулалтын тайлан /Үйлдвэрийн ашиглалт, ажил гүйцэтгэх/', contest_center)
			sheet.merge_range(2+37, 0, 3+37, 0, u'№', contest_center)
			sheet.merge_range(2+37, 1, 3+37, 1, u'Нэр', contest_center)
			sheet.merge_range(2+37, 2, 3+37, 2, u'Нэгж', contest_center)
			sheet.merge_range(2+37, 3, 3+37, 3, u'Нийт', contest_center)
			sheet.merge_range(2+37, 4, 2+37, 15, self.year, contest_center)
			sheet.write(3+37, 4, u'1', contest_center)
			sheet.write(3+37, 5, u'2', contest_center)
			sheet.write(3+37, 6, u'3', contest_center)
			sheet.write(3+37, 7, u'4', contest_center)
			sheet.write(3+37, 8, u'5', contest_center)
			sheet.write(3+37, 9, u'6', contest_center)
			sheet.write(3+37, 10, u'7', contest_center)
			sheet.write(3+37, 11, u'8', contest_center)
			sheet.write(3+37, 12, u'9', contest_center)
			sheet.write(3+37, 13, u'10', contest_center)
			sheet.write(3+37, 14, u'11', contest_center)
			sheet.write(3+37, 15, u'12', contest_center)
			sheet.write(4+37, 0, u'1', contest_center)
			sheet.write(4+37, 1, u'Борлуулалт, Эхний төлөвлөгөө', contest_center)
			sheet.write(4+37, 2, u'₮', contest_center)
			sheet.write(5+37, 0, u'2', contest_center)
			sheet.write(5+37, 1, u'Борлуулалт, Хүлээгдэж буй бодит', contest_center)
			sheet.write(5+37, 2, u'₮', contest_center)
			sheet.write(6+37, 0, u'2', contest_center)
			sheet.write(6+37, 1, u'Хүлээгдэж буй / Эхний төлөвлөгөө, харьцаа', contest_center)
			sheet.write(6+37, 2, u'%', contest_center)
			sheet.write(7+37, 0, u'3', contest_center)
			sheet.write(7+37, 1, u'Борлуулалт, Гүйцэтгэсэн бодит', contest_center)
			sheet.write(7+37, 2, u'₮', contest_center)
			sheet.write(8+37, 0, u'3', contest_center)
			sheet.write(8+37, 1, u'Гүйцэтгэсэн / Эхний төлөвлөгөө, харьцаа', contest_center)
			sheet.write(8+37, 2, u'%', contest_center)
			sheet.write(9+37, 0, u'3', contest_center)
			sheet.write(9+37, 1, u'Гүйцэтгэсэн / Хүлээгдэж буй бодит, харьцаа', contest_center)
			sheet.write(9+37, 2, u'%', contest_center)

			sheet.write(1+47, 1, u'Борлуулалтын мөнгөн урсгалын тайлан', contest_center)
			sheet.merge_range(2+47, 0, 3+47, 0, u'№', contest_center)
			sheet.merge_range(2+47, 1, 3+47, 1, u'Нэр', contest_center)
			sheet.merge_range(2+47, 2, 3+47, 2, u'Нэгж', contest_center)
			sheet.merge_range(2+47, 3, 3+47, 3, u'Нийт', contest_center)
			sheet.merge_range(2+47, 4, 2+47, 15, self.year, contest_center)
			sheet.write(3+47, 4, u'1', contest_center)
			sheet.write(3+47, 5, u'2', contest_center)
			sheet.write(3+47, 6, u'3', contest_center)
			sheet.write(3+47, 7, u'4', contest_center)
			sheet.write(3+47, 8, u'5', contest_center)
			sheet.write(3+47, 9, u'6', contest_center)
			sheet.write(3+47, 10, u'7', contest_center)
			sheet.write(3+47, 11, u'8', contest_center)
			sheet.write(3+47, 12, u'9', contest_center)
			sheet.write(3+47, 13, u'10', contest_center)
			sheet.write(3+47, 14, u'11', contest_center)
			sheet.write(3+47, 15, u'12', contest_center)
			sheet.write(4+47, 0, u'1', contest_center)
			sheet.write(4+47, 1, u'Борлуулалт, Эхний төлөвлөгөө', contest_center)
			sheet.write(4+47, 2, u'₮', contest_center)
			sheet.write(5+47, 0, u'2', contest_center)
			sheet.write(5+47, 1, u'Борлуулалт, Хүлээгдэж буй бодит', contest_center)
			sheet.write(5+47, 2, u'₮', contest_center)
			sheet.write(6+47, 0, u'2', contest_center)
			sheet.write(6+47, 1, u'Хүлээгдэж буй / Эхний төлөвлөгөө, харьцаа', contest_center)
			sheet.write(6+47, 2, u'%', contest_center)
			sheet.write(7+47, 0, u'3', contest_center)
			sheet.write(7+47, 1, u'Борлуулалт, Гүйцэтгэсэн бодит', contest_center)
			sheet.write(7+47, 2, u'₮', contest_center)
			sheet.write(8+47, 0, u'3', contest_center)
			sheet.write(8+47, 1, u'Гүйцэтгэсэн / Эхний төлөвлөгөө, харьцаа', contest_center)
			sheet.write(8+47, 2, u'%', contest_center)
			sheet.write(9+47, 0, u'3', contest_center)
			sheet.write(9+47, 1, u'Гүйцэтгэсэн / Хүлээгдэж буй бодит, харьцаа', contest_center)
			sheet.write(9+47, 2, u'%', contest_center)

			sheet.write(1+57, 1, u'Борлуулалтын өртгийн тайлан /ханган нийлүүлэлт', contest_center)
			sheet.merge_range(2+57, 0, 3+57, 0, u'№', contest_center)
			sheet.merge_range(2+57, 1, 3+57, 1, u'Нэр', contest_center)
			sheet.merge_range(2+57, 2, 3+57, 2, u'Нэгж', contest_center)
			sheet.merge_range(2+57, 3, 3+57, 3, u'Нийт', contest_center)
			sheet.merge_range(2+57, 4, 2+57, 15, self.year, contest_center)
			sheet.write(3+57, 4, u'1', contest_center)
			sheet.write(3+57, 5, u'2', contest_center)
			sheet.write(3+57, 6, u'3', contest_center)
			sheet.write(3+57, 7, u'4', contest_center)
			sheet.write(3+57, 8, u'5', contest_center)
			sheet.write(3+57, 9, u'6', contest_center)
			sheet.write(3+57, 10, u'7', contest_center)
			sheet.write(3+57, 11, u'8', contest_center)
			sheet.write(3+57, 12, u'9', contest_center)
			sheet.write(3+57, 13, u'10', contest_center)
			sheet.write(3+57, 14, u'11', contest_center)
			sheet.write(3+57, 15, u'12', contest_center)
			sheet.write(4+57, 0, u'1', contest_center)
			sheet.write(4+57, 1, u'ББӨ, Эхний төлөвлөгөө', contest_center)
			sheet.write(4+57, 2, u'₮', contest_center)
			sheet.write(5+57, 0, u'1', contest_center)
			sheet.write(5+57, 1, u'ББӨ / Борлуулалтанд эзлэх %, эхний төлөвлөгөө ', contest_center)
			sheet.write(5+57, 2, u'%', contest_center)
			sheet.write(6+57, 0, u'2', contest_center)
			sheet.write(6+57, 1, u'ББӨ, тооцоогоор', contest_center)
			sheet.write(6+57, 2, u'₮', contest_center)
			sheet.write(7+57, 0, u'2', contest_center)
			sheet.write(7+57, 1, u'ББӨ / Борлуулалтанд эзлэх, тооцсон %', contest_center)
			sheet.write(7+57, 2, u'%', contest_center)
			sheet.write(8+57, 0, u'2', contest_center)
			sheet.write(8+57, 1, u'ББӨ, Тооцооны / эхний төлөвлөлт, харьцаа', contest_center)
			sheet.write(8+57, 2, u'₮', contest_center)
			sheet.write(9+57, 0, u'3', contest_center)
			sheet.write(9+57, 1, u'ББӨ, гүйцэтгэсэн бодит', contest_center)
			sheet.write(9+57, 2, u'%', contest_center)
			sheet.write(10+57, 0, u'3', contest_center)
			sheet.write(10+57, 1, u'ББӨ, / Борлуулалтанд эзлэх, гүйцэтгэсэн %', contest_center)
			sheet.write(10+57, 2, u'%', contest_center)
			sheet.write(11+57, 0, u'3', contest_center)
			sheet.write(11+57, 1, u'ББӨ, Гүйцэтгэсэн / эхний төлөвлөлт, харьцаа', contest_center)
			sheet.write(11+57, 2, u'%', contest_center)
			sheet.write(12+57, 0, u'3', contest_center)
			sheet.write(12+57, 1, u'ББӨ, Гүйцэтгэсэн / тооцсон, харьцаа', contest_center)
			sheet.write(12+57, 2, u'%', contest_center)

			sheet.write(1+69, 1, u'Борлуулалтын бохир ашгийн ("ашиг") тайлан /Ашиглалт', contest_center)
			sheet.merge_range(2+69, 0, 3+69, 0, u'№', contest_center)
			sheet.merge_range(2+69, 1, 3+69, 1, u'Нэр', contest_center)
			sheet.merge_range(2+69, 2, 3+69, 2, u'Нэгж', contest_center)
			sheet.merge_range(2+69, 3, 3+69, 3, u'Нийт', contest_center)
			sheet.merge_range(2+69, 4, 2+69, 15, self.year, contest_center)
			sheet.write(3+69, 4, u'1', contest_center)
			sheet.write(3+69, 5, u'2', contest_center)
			sheet.write(3+69, 6, u'3', contest_center)
			sheet.write(3+69, 7, u'4', contest_center)
			sheet.write(3+69, 8, u'5', contest_center)
			sheet.write(3+69, 9, u'6', contest_center)
			sheet.write(3+69, 10, u'7', contest_center)
			sheet.write(3+69, 11, u'8', contest_center)
			sheet.write(3+69, 12, u'9', contest_center)
			sheet.write(3+69, 13, u'10', contest_center)
			sheet.write(3+69, 14, u'11', contest_center)
			sheet.write(3+69, 15, u'12', contest_center)
			sheet.write(4+69, 0, u'1', contest_center)
			sheet.write(4+69, 1, u'Ашиг, Эхний төлөвлөгөө', contest_center)
			sheet.write(4+69, 2, u'₮', contest_center)
			sheet.write(5+69, 0, u'1', contest_center)
			sheet.write(5+69, 1, u'Ашиг / Борлуулалтанд эзлэх %, эхний төлөвлөгөө ', contest_center)
			sheet.write(5+69, 2, u'%', contest_center)
			sheet.write(6+69, 0, u'2', contest_center)
			sheet.write(6+69, 1, u'Ашиг, тооцоогоор', contest_center)
			sheet.write(6+69, 2, u'₮', contest_center)
			sheet.write(7+69, 0, u'2', contest_center)
			sheet.write(7+69, 1, u'Ашиг / Борлуулалтанд эзлэх, тооцсон %', contest_center)
			sheet.write(7+69, 2, u'%', contest_center)
			sheet.write(8+69, 0, u'2', contest_center)
			sheet.write(8+69, 1, u'Ашиг, Тооцооны / эхний төлөвлөлт, харьцаа', contest_center)
			sheet.write(8+69, 2, u'₮', contest_center)
			sheet.write(9+69, 0, u'3', contest_center)
			sheet.write(9+69, 1, u'Ашиг, гүйцэтгэсэн бодит', contest_center)
			sheet.write(9+69, 2, u'%', contest_center)
			sheet.write(10+69, 0, u'3', contest_center)
			sheet.write(10+69, 1, u'Ашиг, / Борлуулалтанд эзлэх, гүйцэтгэсэн %', contest_center)
			sheet.write(10+69, 2, u'%', contest_center)
			sheet.write(11+69, 0, u'3', contest_center)
			sheet.write(11+69, 1, u'Ашиг, Гүйцэтгэсэн / эхний төлөвлөлт, харьцаа', contest_center)
			sheet.write(11+69, 2, u'%', contest_center)
			sheet.write(12+69, 0, u'3', contest_center)
			sheet.write(12+69, 1, u'Ашиг, Гүйцэтгэсэн / тооцсон, харьцаа', contest_center)
			sheet.write(12+69, 2, u'%', contest_center)

			sheet.write(1+82, 1, u'Борлуулалтын бохир ашгийн ("ашиг") тайлан', contest_center)
			sheet.merge_range(2+82, 0, 3+82, 0, u'№', contest_center)
			sheet.merge_range(2+82, 1, 3+82, 1, u'Нэр', contest_center)
			sheet.merge_range(2+82, 2, 3+82, 2, u'Нэгж', contest_center)
			sheet.merge_range(2+82, 3, 3+82, 3, u'Нийт', contest_center)
			sheet.merge_range(2+82, 4, 2+82, 15, self.year, contest_center)
			sheet.write(3+82, 4, u'1', contest_center)
			sheet.write(3+82, 5, u'2', contest_center)
			sheet.write(3+82, 6, u'3', contest_center)
			sheet.write(3+82, 7, u'4', contest_center)
			sheet.write(3+82, 8, u'5', contest_center)
			sheet.write(3+82, 9, u'6', contest_center)
			sheet.write(3+82, 10, u'7', contest_center)
			sheet.write(3+82, 11, u'8', contest_center)
			sheet.write(3+82, 12, u'9', contest_center)
			sheet.write(3+82, 13, u'10', contest_center)
			sheet.write(3+82, 14, u'11', contest_center)
			sheet.write(3+82, 15, u'12', contest_center)
			sheet.write(4+82, 0, u'1', contest_center)
			sheet.write(4+82, 1, u'Ашиг, Эхний төлөвлөгөө', contest_center)
			sheet.write(4+82, 2, u'₮', contest_center)
			sheet.write(5+82, 0, u'1', contest_center)
			sheet.write(5+82, 1, u'Ашиг / Борлуулалтанд эзлэх %, эхний төлөвлөгөө ', contest_center)
			sheet.write(5+82, 2, u'%', contest_center)
			sheet.write(6+82, 0, u'2', contest_center)
			sheet.write(6+82, 1, u'Ашиг, тооцоогоор', contest_center)
			sheet.write(6+82, 2, u'₮', contest_center)
			sheet.write(7+82, 0, u'2', contest_center)
			sheet.write(7+82, 1, u'Ашиг / Борлуулалтанд эзлэх, тооцсон %', contest_center)
			sheet.write(7+82, 2, u'%', contest_center)
			sheet.write(8+82, 0, u'2', contest_center)
			sheet.write(8+82, 1, u'Ашиг, Тооцооны / эхний төлөвлөлт, харьцаа', contest_center)
			sheet.write(8+82, 2, u'₮', contest_center)
			sheet.write(9+82, 0, u'3', contest_center)
			sheet.write(9+82, 1, u'Ашиг, гүйцэтгэсэн бодит', contest_center)
			sheet.write(9+82, 2, u'%', contest_center)
			sheet.write(10+82, 0, u'3', contest_center)
			sheet.write(10+82, 1, u'Ашиг, / Борлуулалтанд эзлэх, гүйцэтгэсэн %', contest_center)
			sheet.write(10+82, 2, u'%', contest_center)
			sheet.write(11+82, 0, u'3', contest_center)
			sheet.write(11+82, 1, u'Ашиг, Гүйцэтгэсэн / эхний төлөвлөлт, харьцаа', contest_center)
			sheet.write(11+82, 2, u'%', contest_center)
			sheet.write(12+82, 0, u'3', contest_center)
			sheet.write(12+82, 1, u'Ашиг, Гүйцэтгэсэн / тооцсон, харьцаа', contest_center)
			sheet.write(12+82, 2, u'%', contest_center)

			#Борлуулалтын тайлан, нэгтгэл
			sheet.write_formula(4, 3, '{='+self._symbol(13, 3)+'+'+self._symbol(22, 3)+'}', contest_center)
			sheet.write_formula(4, 4, '{='+self._symbol(13, 4)+'+'+self._symbol(22, 4)+'}', contest_center)
			sheet.write_formula(4, 5, '{='+self._symbol(13, 5)+'+'+self._symbol(22, 5)+'}', contest_center)
			sheet.write_formula(4, 6, '{='+self._symbol(4, 5)+'/'+self._symbol(4, 3)+'*100}', contest_center)
			sheet.write_formula(4, 7, '{='+self._symbol(13, 5)+'/'+self._symbol(13, 4)+'}', contest_center)
			sheet.write_formula(4, 8, '{='+self._symbol(13, 3)+'*3}', contest_center)
			sheet.write_formula(4, 9, '{='+self._symbol(32, 4+col)+'+'+self._symbol(32, 5+col)+'+'+self._symbol(32, 6+col)+'}', contest_center)
			sheet.write_formula(4, 10, '{='+self._symbol(34, 4+col)+'+'+self._symbol(34, 5+col)+'+'+self._symbol(34, 6+col)+'}', contest_center)
			sheet.write_formula(4, 11, '{='+self._symbol(4, 10)+'/'+self._symbol(4, 8)+'*100}', contest_center)
			sheet.write_formula(4, 12, '', contest_center)
			sheet.write_formula(4, 13, '{='+self._symbol(31, 3)+'}', contest_center)
			sheet.write_formula(4, 14, '{='+self._symbol(32, 3)+'}', contest_center)
			sheet.write_formula(4, 15, '{='+self._symbol(34, 3)+'}', contest_center)
			sheet.write_formula(4, 16, '{='+self._symbol(4, 15)+'/'+self._symbol(4, 13)+'*100}', contest_center)
			sheet.write_formula(4, 17, '{='+self._symbol(4, 15)+'/'+self._symbol(4, 14)+'*100}', contest_center)

			sheet.write_formula(5, 3, '{='+self._symbol(14, 3)+'+'+self._symbol(23, 3)+'}', contest_center)
			sheet.write_formula(5, 4, '{='+self._symbol(14, 4)+'+'+self._symbol(23, 4)+'}', contest_center)
			sheet.write_formula(5, 5, '{='+self._symbol(14, 5)+'+'+self._symbol(23, 5)+'}', contest_center)
			sheet.write_formula(5, 6, '{='+self._symbol(5, 5)+'/'+self._symbol(5, 3)+'*100}', contest_center)
			sheet.write_formula(5, 7, '{='+self._symbol(14, 5)+'/'+self._symbol(14, 4)+'*100}', contest_center)
			sheet.write_formula(5, 8, '{='+self._symbol(14, 3)+'*3}', contest_center)
			sheet.write_formula(5, 9, '{='+self._symbol(63, 4+col)+'+'+self._symbol(63, 5+col)+'+'+self._symbol(63, 6+col)+'}', contest_center)
			sheet.write_formula(5, 10, '{='+self._symbol(66, 4+col)+'+'+self._symbol(66, 5+col)+'+'+self._symbol(66, 6+col)+'}', contest_center)
			sheet.write_formula(5, 11, '{='+self._symbol(5, 10)+'/'+self._symbol(5, 8)+'*100}', contest_center)
			sheet.write_formula(5, 12, '', contest_center)
			sheet.write_formula(5, 13, '{='+self._symbol(61, 3)+'}', contest_center)
			sheet.write_formula(5, 14, '{='+self._symbol(63, 3)+'}', contest_center)
			sheet.write_formula(5, 15, '{='+self._symbol(44, 3)+'}', contest_center)
			sheet.write_formula(5, 16, '{='+self._symbol(5, 15)+'/'+self._symbol(5, 14)+'*100}', contest_center)
			sheet.write_formula(5, 17, '{='+self._symbol(5, 15)+'/'+self._symbol(5, 14)+'*100}', contest_center)

			sheet.write_formula(6, 3, '{='+self._symbol(15, 3)+'+'+self._symbol(24, 3)+'}', contest_center)
			sheet.write_formula(6, 4, '{='+self._symbol(15, 4)+'+'+self._symbol(24, 4)+'}', contest_center)
			sheet.write_formula(6, 5, '{='+self._symbol(15, 5)+'+'+self._symbol(24, 5)+'}', contest_center)
			sheet.write_formula(6, 6, '{='+self._symbol(6, 5)+'/'+self._symbol(6, 3)+'*100}', contest_center)
			sheet.write_formula(6, 7, '{='+self._symbol(15, 5)+'/'+self._symbol(15, 4)+'*100}', contest_center)
			sheet.write_formula(6, 8, '{='+self._symbol(15, 3)+'*3}', contest_center)
			sheet.write_formula(6, 9, '{='+self._symbol(88, 4+col)+'+'+self._symbol(88, 5+col)+'+'+self._symbol(88, 6+col)+'}', contest_center)
			sheet.write_formula(6, 10, '{='+self._symbol(91, 4+col)+'+'+self._symbol(91, 5+col)+'+'+self._symbol(91, 6+col)+'}', contest_center)
			sheet.write_formula(6, 11, '{='+self._symbol(6, 10)+'/'+self._symbol(6, 8)+'*100}', contest_center)
			sheet.write_formula(6, 12, '', contest_center)
			sheet.write_formula(6, 13, '{='+self._symbol(86, 3)+'}', contest_center)
			sheet.write_formula(6, 14, '{='+self._symbol(88, 3)+'}', contest_center)
			sheet.write_formula(6, 15, '{='+self._symbol(91, 3)+'}', contest_center)
			sheet.write_formula(6, 16, '{='+self._symbol(6, 15)+'/'+self._symbol(6, 15)+'*100}', contest_center)
			sheet.write_formula(6, 17, '{='+self._symbol(6, 15)+'/'+self._symbol(6, 15)+'*100}', contest_center)

			sheet.write_formula(7, 3, '{='+self._symbol(5, 3)+'/'+self._symbol(4, 3)+'*100}', contest_center)
			sheet.write_formula(7, 4, '{='+self._symbol(5, 4)+'/'+self._symbol(4, 4)+'*100}', contest_center)
			sheet.write_formula(7, 5, '{='+self._symbol(5, 5)+'/'+self._symbol(4, 5)+'*100}', contest_center)
			sheet.write_formula(7, 6, '{='+self._symbol(7, 5)+'/'+self._symbol(7, 3)+'*100}', contest_center)
			sheet.write_formula(7, 7, '{='+self._symbol(16, 5)+'/'+self._symbol(16, 4)+'*100}', contest_center)
			sheet.write_formula(7, 8, '{='+self._symbol(5, 8)+'/'+self._symbol(4, 8)+'*100}', contest_center)
			sheet.write_formula(7, 9, '{='+self._symbol(5, 9)+'/'+self._symbol(4, 9)+'*100}', contest_center)
			sheet.write_formula(7, 10, '{='+self._symbol(7, 9)+'/'+self._symbol(7, 7)+'*100}', contest_center)
			sheet.write_formula(7, 11, '{='+self._symbol(7, 9)+'/'+self._symbol(7, 8)+'*100}', contest_center)
			sheet.write_formula(7, 12, '', contest_center)
			sheet.write_formula(7, 13, '{='+self._symbol(5, 13)+'/'+self._symbol(4, 13)+'*100}', contest_center)
			sheet.write_formula(7, 14, '{='+self._symbol(5, 14)+'/'+self._symbol(4, 14)+'*100}', contest_center)
			sheet.write_formula(7, 15, '{='+self._symbol(5, 15)+'/'+self._symbol(4, 15)+'*100}', contest_center)
			sheet.write_formula(7, 16, '{='+self._symbol(7, 15)+'/'+self._symbol(7, 13)+'*100}', contest_center)
			sheet.write_formula(7, 17, '{='+self._symbol(7, 15)+'/'+self._symbol(7, 14)+'*100}', contest_center)

			sheet.write_formula(8, 3, '{='+self._symbol(6, 3)+'/'+self._symbol(4, 3)+'*100}', contest_center)
			sheet.write_formula(8, 4, '{='+self._symbol(6, 4)+'/'+self._symbol(4, 4)+'*100}', contest_center)
			sheet.write_formula(8, 5, '{='+self._symbol(6, 5)+'/'+self._symbol(4, 5)+'*100}', contest_center)
			sheet.write_formula(8, 6, '{='+self._symbol(8, 5)+'/'+self._symbol(8, 3)+'*100}', contest_center)
			sheet.write_formula(8, 7, '{='+self._symbol(17, 5)+'/'+self._symbol(17, 4)+'*100}', contest_center)
			sheet.write_formula(8, 8, '{='+self._symbol(6, 8)+'/'+self._symbol(4, 8)+'*100}', contest_center)
			sheet.write_formula(8, 9, '{='+self._symbol(6, 9)+'/'+self._symbol(4, 9)+'*100}', contest_center)
			sheet.write_formula(8, 10, '{='+self._symbol(8, 9)+'/'+self._symbol(8, 7)+'*100}', contest_center)
			sheet.write_formula(8, 11, '{='+self._symbol(8, 9)+'/'+self._symbol(8, 8)+'*100}', contest_center)
			sheet.write_formula(8, 12, '', contest_center)
			sheet.write_formula(8, 13, '{='+self._symbol(6, 13)+'/'+self._symbol(4, 13)+'*100}', contest_center)
			sheet.write_formula(8, 14, '{='+self._symbol(6, 14)+'/'+self._symbol(4, 14)+'*100}', contest_center)
			sheet.write_formula(8, 15, '{='+self._symbol(6, 15)+'/'+self._symbol(4, 15)+'*100}', contest_center)
			sheet.write_formula(8, 16, '{='+self._symbol(8, 15)+'/'+self._symbol(8, 13)+'*100}', contest_center)
			sheet.write_formula(8, 17, '{='+self._symbol(8, 15)+'/'+self._symbol(8, 14)+'*100}', contest_center)

			#Борлуулалтын тайлан, /ханган нийлүүлэлт/
			sheet.write_formula(13, 3, '{='+self._symbol(31, 4+col)+'+'+self._symbol(31, 5+col)+'+'+self._symbol(31, 6+col)+'}', contest_center)
			sheet.write_formula(13, 4, '{='+self._symbol(32, 4+col)+'+'+self._symbol(32, 5+col)+'+'+self._symbol(32, 6+col)+'}', contest_center)
			sheet.write_formula(13, 5, '{='+self._symbol(34, 4+col)+'+'+self._symbol(34, 5+col)+'+'+self._symbol(34, 6+col)+'}', contest_center)
			sheet.write_formula(13, 6, '{='+self._symbol(13, 5)+'/'+self._symbol(13, 3)+'*100}', contest_center)
			sheet.write_formula(13, 7, '{='+self._symbol(13, 5)+'/'+self._symbol(13, 4)+'*100}', contest_center)
			sheet.write_formula(14, 3, '{='+self._symbol(61, 4+col)+'+'+self._symbol(61, 5+col)+'+'+self._symbol(61, 6+col)+'}', contest_center)
			sheet.write_formula(14, 4, '{='+self._symbol(63, 4+col)+'+'+self._symbol(63, 5+col)+'+'+self._symbol(63, 6+col)+'}', contest_center)
			sheet.write_formula(14, 5, '{='+self._symbol(66, 4+col)+'+'+self._symbol(66, 5+col)+'+'+self._symbol(66, 6+col)+'}', contest_center)
			sheet.write_formula(14, 6, '{='+self._symbol(14, 5)+'/'+self._symbol(14, 3)+'*100}', contest_center)
			sheet.write_formula(14, 7, '{='+self._symbol(14, 5)+'/'+self._symbol(14, 4)+'*100}', contest_center)
			sheet.write_formula(15, 3, '{='+self._symbol(86, 4+col)+'+'+self._symbol(86, 5+col)+'+'+self._symbol(86, 6+col)+'}', contest_center)
			sheet.write_formula(15, 5, '{='+self._symbol(88, 4+col)+'+'+self._symbol(88, 5+col)+'+'+self._symbol(88, 6+col)+'}', contest_center)
			sheet.write_formula(15, 6, '{='+self._symbol(91, 4+col)+'+'+self._symbol(91, 5+col)+'+'+self._symbol(91, 6+col)+'}', contest_center)
			sheet.write_formula(15, 6, '{='+self._symbol(15, 5)+'/'+self._symbol(15, 3)+'*100}', contest_center)
			sheet.write_formula(15, 7, '{='+self._symbol(15, 5)+'/'+self._symbol(15, 4)+'*100}', contest_center)
			sheet.write_formula(16, 3, '{='+self._symbol(14, 3)+'/'+self._symbol(13, 3)+'*100}', contest_center)
			sheet.write_formula(16, 4, '{='+self._symbol(14, 4)+'/'+self._symbol(13, 4)+'*100}', contest_center)
			sheet.write_formula(16, 5, '{='+self._symbol(14, 5)+'/'+self._symbol(13, 5)+'*100}', contest_center)
			sheet.write_formula(16, 6, '{='+self._symbol(16, 5)+'/'+self._symbol(16, 3)+'*100}', contest_center)
			sheet.write_formula(16, 7, '{='+self._symbol(16, 5)+'/'+self._symbol(16, 4)+'*100}', contest_center)
			sheet.write_formula(17, 3, '{='+self._symbol(15, 3)+'/'+self._symbol(13, 3)+'*100}', contest_center)
			sheet.write_formula(17, 4, '{='+self._symbol(15, 4)+'/'+self._symbol(13, 4)+'*100}', contest_center)
			sheet.write_formula(17, 5, '{='+self._symbol(15, 5)+'/'+self._symbol(13, 5)+'*100}', contest_center)
			sheet.write_formula(17, 6, '{='+self._symbol(17, 5)+'/'+self._symbol(17, 3)+'*100}', contest_center)
			sheet.write_formula(17, 7, '{='+self._symbol(17, 5)+'/'+self._symbol(17, 4)+'*100}', contest_center)

			# Борлуулалтын тайлан, /ашиглалт, угсралт/
			sheet.write_formula(22, 3, '{='+self._symbol(41, 4+col)+'+'+self._symbol(41, 5+col)+'+'+self._symbol(41, 6)+'}', contest_center)
			sheet.write_formula(22, 4, '{='+self._symbol(41, 4+col)+'+'+self._symbol(41, 5+col)+'+'+self._symbol(41, 6)+'}', contest_center)
			sheet.write_formula(22, 5, '{='+self._symbol(41, 4+col)+'+'+self._symbol(41, 5+col)+'+'+self._symbol(41, 6)+'}', contest_center)
			sheet.write_formula(22, 6, '{='+self._symbol(22, 5)+'/'+self._symbol(22, 3)+'*100}', contest_center)
			sheet.write_formula(22, 7, '{='+self._symbol(22, 5)+'/'+self._symbol(22, 4)+'*100}', contest_center)
			sheet.write_formula(23, 3, '{='+self._symbol(22, 3)+'*0.8}', contest_center)
			sheet.write_formula(23, 4, '{='+self._symbol(22, 4)+'*0.8}', contest_center)
			sheet.write_formula(23, 5, '{='+self._symbol(22, 5)+'*0.8}', contest_center)
			sheet.write_formula(23, 6, '{='+self._symbol(23, 5)+'/'+self._symbol(23, 3)+'*100}', contest_center)
			sheet.write_formula(23, 7, '{='+self._symbol(23, 5)+'/'+self._symbol(23, 4)+'*100}', contest_center)
			sheet.write_formula(24, 3, '{='+self._symbol(22, 3)+'-'+self._symbol(23, 3)+'}', contest_center)
			sheet.write_formula(24, 4, '{='+self._symbol(22, 4)+'-'+self._symbol(23, 4)+'}', contest_center)
			sheet.write_formula(24, 5, '{='+self._symbol(22, 5)+'-'+self._symbol(23, 5)+'}', contest_center)
			sheet.write_formula(24, 6, '{='+self._symbol(24, 5)+'/'+self._symbol(24, 3)+'*100}', contest_center)
			sheet.write_formula(24, 7, '{='+self._symbol(24, 5)+'/'+self._symbol(24, 4)+'*100}', contest_center)
			sheet.write_formula(25, 3, '{='+self._symbol(23, 3)+'/'+self._symbol(22, 3)+'*100}', contest_center)
			sheet.write_formula(25, 4, '{='+self._symbol(23, 4)+'/'+self._symbol(22, 4)+'*100}', contest_center)
			sheet.write_formula(25, 5, '{='+self._symbol(23, 5)+'/'+self._symbol(22, 5)+'*100}', contest_center)
			sheet.write_formula(25, 6, '{='+self._symbol(25, 5)+'/'+self._symbol(25, 3)+'*100}', contest_center)
			sheet.write_formula(25, 7, '{='+self._symbol(25, 5)+'/'+self._symbol(25, 4)+'*100}', contest_center)
			sheet.write_formula(26, 3, '{='+self._symbol(24, 3)+'/'+self._symbol(22, 3)+'*100}', contest_center)
			sheet.write_formula(26, 4, '{='+self._symbol(24, 4)+'/'+self._symbol(22, 4)+'*100}', contest_center)
			sheet.write_formula(26, 5, '{='+self._symbol(24, 5)+'/'+self._symbol(22, 5)+'*100}', contest_center)
			sheet.write_formula(26, 6, '{='+self._symbol(26, 5)+'/'+self._symbol(26, 3)+'*100}', contest_center)
			sheet.write_formula(26, 7, '{='+self._symbol(26, 5)+'/'+self._symbol(26, 4)+'*100}', contest_center)

			#Борлуулалтын тайлан, /ханган нийлүүлэлт/
			for i in self.line_ids.filtered(lambda r: r.type == '1'):
				sheet.write(31, 4, sum(i.mapped('first')), contest_center)
				sheet.write(31, 5, sum(i.mapped('second')), contest_center)
				sheet.write(31, 6, sum(i.mapped('third')), contest_center)
				sheet.write(31, 7, sum(i.mapped('four')), contest_center)
				sheet.write(31, 8, sum(i.mapped('five')), contest_center)
				sheet.write(31, 9, sum(i.mapped('six')), contest_center)
				sheet.write(31, 10, sum(i.mapped('seven')), contest_center)
				sheet.write(31, 11, sum(i.mapped('eight')), contest_center)
				sheet.write(31, 12, sum(i.mapped('nine')), contest_center)
				sheet.write(31, 13, sum(i.mapped('ten')), contest_center)
				sheet.write(31, 14, sum(i.mapped('eleven')), contest_center)
				sheet.write(31, 15, sum(i.mapped('twelve')), contest_center)
			for i in self.line_ids2.filtered(lambda r: r.type == '1'):
				sheet.write(32, 4, sum(i.mapped('first')), contest_center)
				sheet.write(32, 5, sum(i.mapped('second')), contest_center)
				sheet.write(32, 6, sum(i.mapped('third')), contest_center)
				sheet.write(32, 7, sum(i.mapped('four')), contest_center)
				sheet.write(32, 8, sum(i.mapped('five')), contest_center)
				sheet.write(32, 9, sum(i.mapped('six')), contest_center)
				sheet.write(32, 10, sum(i.mapped('seven')), contest_center)
				sheet.write(32, 11, sum(i.mapped('eight')), contest_center)
				sheet.write(32, 12, sum(i.mapped('nine')), contest_center)
				sheet.write(32, 13, sum(i.mapped('ten')), contest_center)
				sheet.write(32, 14, sum(i.mapped('eleven')), contest_center)
				sheet.write(32, 15, sum(i.mapped('twelve')), contest_center)
			sheet.write(34, 4, sum(sale_order_line.search([('product_id.detailed_type','=','product'),('order_id.date_order','ilike',self.year+'-01')]).mapped('price_subtotal')), contest_center)
			sheet.write(34, 5, sum(sale_order_line.search([('product_id.detailed_type','=','product'),('order_id.date_order','ilike',self.year+'-02')]).mapped('price_subtotal')), contest_center)
			sheet.write(34, 6, sum(sale_order_line.search([('product_id.detailed_type','=','product'),('order_id.date_order','ilike',self.year+'-03')]).mapped('price_subtotal')), contest_center)
			sheet.write(34, 7, sum(sale_order_line.search([('product_id.detailed_type','=','product'),('order_id.date_order','ilike',self.year+'-04')]).mapped('price_subtotal')), contest_center)
			sheet.write(34, 8, sum(sale_order_line.search([('product_id.detailed_type','=','product'),('order_id.date_order','ilike',self.year+'-05')]).mapped('price_subtotal')), contest_center)
			sheet.write(34, 9, sum(sale_order_line.search([('product_id.detailed_type','=','product'),('order_id.date_order','ilike',self.year+'-06')]).mapped('price_subtotal')), contest_center)
			sheet.write(34, 10, sum(sale_order_line.search([('product_id.detailed_type','=','product'),('order_id.date_order','ilike',self.year+'-07')]).mapped('price_subtotal')), contest_center)
			sheet.write(34, 11, sum(sale_order_line.search([('product_id.detailed_type','=','product'),('order_id.date_order','ilike',self.year+'-08')]).mapped('price_subtotal')), contest_center)
			sheet.write(34, 12, sum(sale_order_line.search([('product_id.detailed_type','=','product'),('order_id.date_order','ilike',self.year+'-09')]).mapped('price_subtotal')), contest_center)
			sheet.write(34, 13, sum(sale_order_line.search([('product_id.detailed_type','=','product'),('order_id.date_order','ilike',self.year+'-10')]).mapped('price_subtotal')), contest_center)
			sheet.write(34, 14, sum(sale_order_line.search([('product_id.detailed_type','=','product'),('order_id.date_order','ilike',self.year+'-11')]).mapped('price_subtotal')), contest_center)
			sheet.write(34, 15, sum(sale_order_line.search([('product_id.detailed_type','=','product'),('order_id.date_order','ilike',self.year+'-12')]).mapped('price_subtotal')), contest_center)
			sheet.write_formula(31, 3, '{=sum('+self._symbol(31, 4)+':'+self._symbol(31, 15)+')}', contest_center)
			sheet.write_formula(32, 3, '{=sum('+self._symbol(32, 4)+':'+self._symbol(32, 15)+')}', contest_center)
			sheet.write_formula(33, 3, '{='+self._symbol(32, 3)+'/'+self._symbol(31, 3)+'*100}', contest_center)
			sheet.write_formula(34, 3, '{=sum('+self._symbol(34, 4)+':'+self._symbol(34, 15)+')}', contest_center)
			sheet.write_formula(35, 3, '{='+self._symbol(34, 3)+'/'+self._symbol(31, 3)+'*100}', contest_center)
			sheet.write_formula(36, 3, '{='+self._symbol(34, 3)+'/'+self._symbol(32, 3)+'*100}', contest_center)

			#Борлуулалтын тайлан /Үйлдвэрийн ашиглалт, ажил гүйцэтгэх/
			for i in self.line_ids.filtered(lambda r: r.type == '2'):
				sheet.write(41, 4, sum(i.mapped('first')), contest_center)
				sheet.write(41, 5, sum(i.mapped('second')), contest_center)
				sheet.write(41, 6, sum(i.mapped('third')), contest_center)
				sheet.write(41, 7, sum(i.mapped('four')), contest_center)
				sheet.write(41, 8, sum(i.mapped('five')), contest_center)
				sheet.write(41, 9, sum(i.mapped('six')), contest_center)
				sheet.write(41, 10, sum(i.mapped('seven')), contest_center)
				sheet.write(41, 11, sum(i.mapped('eight')), contest_center)
				sheet.write(41, 12, sum(i.mapped('nine')), contest_center)
				sheet.write(41, 13, sum(i.mapped('ten')), contest_center)
				sheet.write(41, 14, sum(i.mapped('eleven')), contest_center)
				sheet.write(41, 15, sum(i.mapped('twelve')), contest_center)
			for i in self.line_ids2.filtered(lambda r: r.type == '2'):
				sheet.write(42, 4, sum(i.mapped('first')), contest_center)
				sheet.write(42, 5, sum(i.mapped('second')), contest_center)
				sheet.write(42, 6, sum(i.mapped('third')), contest_center)
				sheet.write(42, 7, sum(i.mapped('four')), contest_center)
				sheet.write(42, 8, sum(i.mapped('five')), contest_center)
				sheet.write(42, 9, sum(i.mapped('six')), contest_center)
				sheet.write(42, 10, sum(i.mapped('seven')), contest_center)
				sheet.write(42, 11, sum(i.mapped('eight')), contest_center)
				sheet.write(42, 12, sum(i.mapped('nine')), contest_center)
				sheet.write(42, 13, sum(i.mapped('ten')), contest_center)
				sheet.write(42, 14, sum(i.mapped('eleven')), contest_center)
				sheet.write(42, 15, sum(i.mapped('twelve')), contest_center)
			sheet.write(44, 4, sum(sale_order_line.search([('product_id.detailed_type','=','service'),('order_id.date_order','ilike',self.year+'-01')]).mapped('price_subtotal')), contest_center)
			sheet.write(44, 5, sum(sale_order_line.search([('product_id.detailed_type','=','service'),('order_id.date_order','ilike',self.year+'-02')]).mapped('price_subtotal')), contest_center)
			sheet.write(44, 6, sum(sale_order_line.search([('product_id.detailed_type','=','service'),('order_id.date_order','ilike',self.year+'-03')]).mapped('price_subtotal')), contest_center)
			sheet.write(44, 7, sum(sale_order_line.search([('product_id.detailed_type','=','service'),('order_id.date_order','ilike',self.year+'-04')]).mapped('price_subtotal')), contest_center)
			sheet.write(44, 8, sum(sale_order_line.search([('product_id.detailed_type','=','service'),('order_id.date_order','ilike',self.year+'-05')]).mapped('price_subtotal')), contest_center)
			sheet.write(44, 9, sum(sale_order_line.search([('product_id.detailed_type','=','service'),('order_id.date_order','ilike',self.year+'-06')]).mapped('price_subtotal')), contest_center)
			sheet.write(44, 10, sum(sale_order_line.search([('product_id.detailed_type','=','service'),('order_id.date_order','ilike',self.year+'-07')]).mapped('price_subtotal')), contest_center)
			sheet.write(44, 11, sum(sale_order_line.search([('product_id.detailed_type','=','service'),('order_id.date_order','ilike',self.year+'-08')]).mapped('price_subtotal')), contest_center)
			sheet.write(44, 12, sum(sale_order_line.search([('product_id.detailed_type','=','service'),('order_id.date_order','ilike',self.year+'-09')]).mapped('price_subtotal')), contest_center)
			sheet.write(44, 13, sum(sale_order_line.search([('product_id.detailed_type','=','service'),('order_id.date_order','ilike',self.year+'-10')]).mapped('price_subtotal')), contest_center)
			sheet.write(44, 14, sum(sale_order_line.search([('product_id.detailed_type','=','service'),('order_id.date_order','ilike',self.year+'-11')]).mapped('price_subtotal')), contest_center)
			sheet.write(44, 15, sum(sale_order_line.search([('product_id.detailed_type','=','service'),('order_id.date_order','ilike',self.year+'-12')]).mapped('price_subtotal')), contest_center)
			sheet.write_formula(41, 3, '{=sum('+self._symbol(31, 4)+':'+self._symbol(31, 15)+')}', contest_center)
			sheet.write_formula(42, 3, '{=sum('+self._symbol(32, 4)+':'+self._symbol(32, 15)+')}', contest_center)
			sheet.write_formula(43, 3, '{='+self._symbol(32, 3)+'/'+self._symbol(31, 3)+'*100}', contest_center)
			sheet.write_formula(44, 3, '{=sum('+self._symbol(34, 4)+':'+self._symbol(34, 15)+')}', contest_center)
			sheet.write_formula(45, 3, '{='+self._symbol(34, 3)+'/'+self._symbol(31, 3)+'*100}', contest_center)
			sheet.write_formula(46, 3, '{='+self._symbol(34, 3)+'/'+self._symbol(32, 3)+'*100}', contest_center)

			#Борлуулалтын мөнгөн урсгалын тайлан
			for i in self.line_ids3:
				sheet.write(52, 4, sum(i.mapped('first')), contest_center)
				sheet.write(52, 5, sum(i.mapped('second')), contest_center)
				sheet.write(52, 6, sum(i.mapped('third')), contest_center)
				sheet.write(52, 7, sum(i.mapped('four')), contest_center)
				sheet.write(52, 8, sum(i.mapped('five')), contest_center)
				sheet.write(52, 9, sum(i.mapped('six')), contest_center)
				sheet.write(52, 10, sum(i.mapped('seven')), contest_center)
				sheet.write(52, 11, sum(i.mapped('eight')), contest_center)
				sheet.write(52, 12, sum(i.mapped('nine')), contest_center)
				sheet.write(52, 13, sum(i.mapped('ten')), contest_center)
				sheet.write(52, 14, sum(i.mapped('eleven')), contest_center)
				sheet.write(52, 15, sum(i.mapped('twelve')), contest_center)
			sheet.write(54, 4, sum(sale_order.search([('date_order','ilike',self.year+'-01')]).mapped('tulsun_tulbur')), contest_center)
			sheet.write(54, 5, sum(sale_order.search([('date_order','ilike',self.year+'-02')]).mapped('tulsun_tulbur')), contest_center)
			sheet.write(54, 6, sum(sale_order.search([('date_order','ilike',self.year+'-03')]).mapped('tulsun_tulbur')), contest_center)
			sheet.write(54, 7, sum(sale_order.search([('date_order','ilike',self.year+'-04')]).mapped('tulsun_tulbur')), contest_center)
			sheet.write(54, 8, sum(sale_order.search([('date_order','ilike',self.year+'-05')]).mapped('tulsun_tulbur')), contest_center)
			sheet.write(54, 9, sum(sale_order.search([('date_order','ilike',self.year+'-06')]).mapped('tulsun_tulbur')), contest_center)
			sheet.write(54, 10, sum(sale_order.search([('date_order','ilike',self.year+'-07')]).mapped('tulsun_tulbur')), contest_center)
			sheet.write(54, 11, sum(sale_order.search([('date_order','ilike',self.year+'-08')]).mapped('tulsun_tulbur')), contest_center)
			sheet.write(54, 12, sum(sale_order.search([('date_order','ilike',self.year+'-09')]).mapped('tulsun_tulbur')), contest_center)
			sheet.write(54, 13, sum(sale_order.search([('date_order','ilike',self.year+'-10')]).mapped('tulsun_tulbur')), contest_center)
			sheet.write(54, 14, sum(sale_order.search([('date_order','ilike',self.year+'-11')]).mapped('tulsun_tulbur')), contest_center)
			sheet.write(54, 15, sum(sale_order.search([('date_order','ilike',self.year+'-12')]).mapped('tulsun_tulbur')), contest_center)
			sheet.write_formula(51, 3, '{=sum('+self._symbol(51, 4)+':'+self._symbol(51, 15)+')}', contest_center)
			sheet.write_formula(52, 3, '{=sum('+self._symbol(52, 4)+':'+self._symbol(52, 15)+')}', contest_center)
			sheet.write_formula(53, 3, '{='+self._symbol(52, 3)+'/'+self._symbol(51, 3)+'*100}', contest_center)
			sheet.write_formula(54, 3, '{=sum('+self._symbol(54, 4)+':'+self._symbol(54, 15)+')}', contest_center)
			sheet.write_formula(55, 3, '{='+self._symbol(54, 3)+'/'+self._symbol(51, 3)+'*100}', contest_center)
			sheet.write_formula(56, 3, '{='+self._symbol(54, 3)+'/'+self._symbol(52, 3)+'*100}', contest_center)

			# Борлуулалтын өртгийн тайлан /ханган нийлүүлэлт
			# sheet.write_formula(66, i+4, '', contest_center) #asuuh
			sheet.write_formula(61, 3, '{=sum('+self._symbol(61, 4)+':'+self._symbol(61, 15)+')}', contest_center)
			sheet.write_formula(62, 3, '{=('+self._symbol(61, 3)+'/'+self._symbol(31, 3)+'*100)}', contest_center)
			sheet.write_formula(63, 3, '{=sum('+self._symbol(63, 4)+':'+self._symbol(63, 15)+')}', contest_center)
			sheet.write_formula(64, 3, '{=('+self._symbol(63, 3)+'/'+self._symbol(32, 3)+'*100)}', contest_center)
			sheet.write_formula(65, 3, '{=('+self._symbol(63, 3)+'/'+self._symbol(31, 3)+'*100)}', contest_center)
			sheet.write_formula(66, 3, '{=sum('+self._symbol(66, 4)+':'+self._symbol(66, 15)+')}', contest_center)
			sheet.write_formula(67, 3, '{=('+self._symbol(66, 3)+'/'+self._symbol(34, 3)+'*100)}', contest_center)
			sheet.write_formula(68, 3, '{=('+self._symbol(66, 3)+'/'+self._symbol(61, 3)+'*100)}', contest_center)
			sheet.write_formula(68, 3, '{=('+self._symbol(66, 3)+'/'+self._symbol(63, 3)+'*100)}', contest_center)

			# Борлуулалтын бохир ашгийн ("ашиг") тайлан /Ашиглалт
			sheet.write_formula(73, 3, '{=sum('+self._symbol(73, 4)+':'+self._symbol(73, 15)+')}', contest_center)
			sheet.write_formula(74, 3, '{=average('+self._symbol(74, 4)+':'+self._symbol(74, 15)+')}', contest_center)
			sheet.write_formula(75, 3, '{=sum('+self._symbol(75, 4)+':'+self._symbol(75, 15)+')}', contest_center)
			sheet.write_formula(76, 3, '{=average('+self._symbol(76, 4)+':'+self._symbol(76, 15)+')}', contest_center)
			sheet.write_formula(77, 3, '{=average('+self._symbol(77, 4)+':'+self._symbol(77, 15)+')}', contest_center)
			sheet.write_formula(78, 3, '{=sum('+self._symbol(78, 4)+':'+self._symbol(78, 15)+')}', contest_center)
			sheet.write_formula(79, 3, '{=average('+self._symbol(79, 4)+':'+self._symbol(79, 15)+')}', contest_center)
			sheet.write_formula(80, 3, '{=average('+self._symbol(80, 4)+':'+self._symbol(80, 15)+')}', contest_center)
			sheet.write_formula(81, 3, '{=average('+self._symbol(81, 4)+':'+self._symbol(81, 15)+')}', contest_center)

			# Борлуулалтын бохир ашгийн ("ашиг") тайлан
			sheet.write_formula(86, 3, '{=sum('+self._symbol(86, 4)+':'+self._symbol(86, 15)+')}', contest_center)
			sheet.write_formula(87, 3, '{=average('+self._symbol(87, 4)+':'+self._symbol(87, 15)+')}', contest_center)
			sheet.write_formula(88, 3, '{=sum('+self._symbol(88, 4)+':'+self._symbol(88, 15)+')}', contest_center)
			sheet.write_formula(89, 3, '{=average('+self._symbol(89, 4)+':'+self._symbol(89, 15)+')}', contest_center)
			sheet.write_formula(90, 3, '{=average('+self._symbol(90, 4)+':'+self._symbol(90, 15)+')}', contest_center)
			sheet.write_formula(91, 3, '{=sum('+self._symbol(91, 4)+':'+self._symbol(91, 15)+')}', contest_center)
			sheet.write_formula(92, 3, '{=average('+self._symbol(92, 4)+':'+self._symbol(92, 15)+')}', contest_center)
			sheet.write_formula(93, 3, '{=average('+self._symbol(93, 4)+':'+self._symbol(93, 15)+')}', contest_center)
			sheet.write_formula(94, 3, '{=average('+self._symbol(94, 4)+':'+self._symbol(94, 15)+')}', contest_center)

			# Сар loop
			for i in range(12):
				sheet.write_formula(33, i+4, '{='+self._symbol(32, i+4)+'/'+self._symbol(31, i+4)+'*100}', contest_center)
				sheet.write_formula(35, i+4, '{='+self._symbol(34, i+4)+'/'+self._symbol(31, i+4)+'*100}', contest_center)
				sheet.write_formula(36, i+4, '{='+self._symbol(35, i+4)+'/'+self._symbol(33, i+4)+'*100}', contest_center)
				sheet.write_formula(43, i+4, '{='+self._symbol(42, i+4)+'/'+self._symbol(41, i+4)+'*100}', contest_center)
				sheet.write_formula(45, i+4, '{='+self._symbol(44, i+4)+'/'+self._symbol(41, i+4)+'*100}', contest_center)
				sheet.write_formula(46, i+4, '{='+self._symbol(45, i+4)+'/'+self._symbol(43, i+4)+'*100}', contest_center)
				sheet.write_formula(51, i+4, '{='+self._symbol(31, i+4)+'+'+self._symbol(41, i+4)+'}', contest_center)
				sheet.write_formula(53, i+4, '{='+self._symbol(52, i+4)+'/'+self._symbol(51, i+4)+'*100}', contest_center)
				sheet.write_formula(55, i+4, '{='+self._symbol(54, i+4)+'/'+self._symbol(51, i+4)+'*100}', contest_center)
				sheet.write_formula(56, i+4, '{='+self._symbol(54, i+4)+'/'+self._symbol(52, i+4)+'*100}', contest_center)
				sheet.write_formula(61, i+4, '{='+self._symbol(31, i+4)+'*0.8}', contest_center)
				sheet.write_formula(62, i+4, '{='+self._symbol(61, i+4)+'/'+self._symbol(31, i+4)+'*100}', contest_center)
				sheet.write_formula(63, i+4, '{='+self._symbol(34, i+4)+'*0.8}', contest_center)
				sheet.write_formula(64, i+4, '{=+'+self._symbol(63, i+4)+'/'+self._symbol(32, i+4)+'*100}', contest_center)
				sheet.write_formula(65, i+4, '{=+'+self._symbol(63, i+4)+'/'+self._symbol(31, i+4)+'*100}', contest_center)
				sheet.write_formula(67, i+4, '{=+'+self._symbol(66, i+4)+'/'+self._symbol(34, i+4)+'*100}', contest_center)
				sheet.write_formula(68, i+4, '{=+'+self._symbol(66, i+4)+'/'+self._symbol(61, i+4)+'*100}', contest_center)
				sheet.write_formula(69, i+4, '{=+'+self._symbol(66, i+4)+'/'+self._symbol(63, i+4)+'*100}', contest_center)
				sheet.write_formula(73, i+4, '{=+'+self._symbol(41, i+4)+'-'+self._symbol(41, i+4)+'*0.8}', contest_center)
				sheet.write_formula(74, i+4, '{=+'+self._symbol(73, i+4)+'/'+self._symbol(41, i+4)+'*100}', contest_center)
				sheet.write_formula(75, i+4, '{=+'+self._symbol(41, i+4)+'-'+self._symbol(41, i+4)+'*0.8}', contest_center)
				sheet.write_formula(76, i+4, '{=+'+self._symbol(75, i+4)+'/'+self._symbol(41, i+4)+'*100}', contest_center)
				sheet.write_formula(77, i+4, '{=+'+self._symbol(75, i+4)+'/('+self._symbol(41, i+4)+')*100}', contest_center)
				# sheet.write_formula(78, i+4, '', contest_center) #asuuh
				sheet.write_formula(79, i+4, '{=+'+self._symbol(78, i+4)+'/'+self._symbol(41, i+4)+'*100}', contest_center)
				sheet.write_formula(80, i+4, '{=+'+self._symbol(78, i+4)+'/'+self._symbol(75, i+4)+'*100}', contest_center)
				sheet.write_formula(81, i+4, '{=+'+self._symbol(78, i+4)+'/'+self._symbol(75, i+4)+'*100}', contest_center)
				sheet.write_formula(86, i+4, '{=+'+self._symbol(31, i+4)+'-'+self._symbol(61, i+4)+'}', contest_center)
				sheet.write_formula(87, i+4, '{=+'+self._symbol(86, i+4)+'/'+self._symbol(31, i+4)+'*100}', contest_center)
				sheet.write_formula(88, i+4, '{=+'+self._symbol(32, i+4)+'-'+self._symbol(63, i+4)+'}', contest_center)
				sheet.write_formula(89, i+4, '{=+'+self._symbol(88, i+4)+'/'+self._symbol(31, i+4)+'*100}', contest_center)
				sheet.write_formula(90, i+4, '{=+'+self._symbol(88, i+4)+'/'+self._symbol(32, i+4)+'*100}', contest_center)
				sheet.write_formula(91, i+4, '{=+'+self._symbol(34, i+4)+'+'+self._symbol(66, i+4)+'}', contest_center)
				sheet.write_formula(92, i+4, '{=+'+self._symbol(91, i+4)+'/'+self._symbol(31, i+4)+'*100}', contest_center)
				sheet.write_formula(93, i+4, '{=+'+self._symbol(91, i+4)+'/'+self._symbol(88, i+4)+'*100}', contest_center)
				sheet.write_formula(94, i+4, '{=+'+self._symbol(91, i+4)+'/'+self._symbol(88, i+4)+'*100}', contest_center)
		else:
			raise UserError(u'Төлөвлөгөө хоосон байна.')
		workbook.close()
		out = base64.encodebytes(output.getvalue())
		excel_id = self.env['report.excel.output'].create({'data': out, 'name': file_name})
		return {'type': 'ir.actions.act_url', 'url': "web/content/?model=report.excel.output&id=%d&filename_field=filename&download=true&field=data&filename=%s" % (excel_id.id, excel_id.name), 'target': 'new'}

	def _symbol(self, row, col):
		return self._symbol_col(col) + str(row+1)

	def _symbol_col(self, col):
		excelCol = str()
		div = col+1
		while div:
			(div, mod) = divmod(div-1, 26)
			excelCol = chr(mod + 65) + excelCol
		return excelCol

class SalePlanLine(models.Model):
	_name='sale.plan.line'
	_description = 'Sale Plan Line'
	_sql_constraints = [('type_uniq', 'unique(type,parent_id)', u'Нэг төлөвлөгөөнд төрөл давхардахгүй!')]

	parent_id = fields.Many2one('sale.plan', 'Parent ID')
	type = fields.Selection([("1", "ханган нийлүүлэлт"), ("2", "ашиглалт, угсралт")], string='Төрөл', required=True)
	first = fields.Float('1-р сар')
	second = fields.Float('2-р сар')
	third = fields.Float('3-р сар')
	four = fields.Float('4-р сар')
	five = fields.Float('5-р сар')
	six = fields.Float('6-р сар')
	seven = fields.Float('7-р сар')
	eight = fields.Float('8-р сар')
	nine = fields.Float('9-р сар')
	ten = fields.Float('10-р сар')
	eleven = fields.Float('11-р сар')
	twelve = fields.Float('12-р сар')

class SalePlanLineSecond(models.Model):
	_name='sale.plan.line.second'
	_description = 'Sale Plan Line Second'
	_sql_constraints = [('type_uniq', 'unique(type,parent_id)', u'Нэг төлөвлөгөөнд төрөл давхардахгүй!')]

	parent_id = fields.Many2one('sale.plan', 'Parent ID')
	type = fields.Selection([("1", "ханган нийлүүлэлт"), ("2", "ашиглалт, угсралт")], string='Төрөл', required=True)
	first = fields.Float('1-р сар')
	second = fields.Float('2-р сар')
	third = fields.Float('3-р сар')
	four = fields.Float('4-р сар')
	five = fields.Float('5-р сар')
	six = fields.Float('6-р сар')
	seven = fields.Float('7-р сар')
	eight = fields.Float('8-р сар')
	nine = fields.Float('9-р сар')
	ten = fields.Float('10-р сар')
	eleven = fields.Float('11-р сар')
	twelve = fields.Float('12-р сар')

class SalePlanLineThird(models.Model):
	_name='sale.plan.line.third'
	_description = 'Sale Plan Line Third'

	parent_id = fields.Many2one('sale.plan', 'Parent ID')
	first = fields.Float('1-р сар')
	second = fields.Float('2-р сар')
	third = fields.Float('3-р сар')
	four = fields.Float('4-р сар')
	five = fields.Float('5-р сар')
	six = fields.Float('6-р сар')
	seven = fields.Float('7-р сар')
	eight = fields.Float('8-р сар')
	nine = fields.Float('9-р сар')
	ten = fields.Float('10-р сар')
	eleven = fields.Float('11-р сар')
	twelve = fields.Float('12-р сар')